/** Even Fibonacci Sum: Write a method that returns the sum of all even Fibonacci numbers.
 *  Consider all Fibonacci numbers that are less than or equal to n. Each new element in the
 *  Fibonacci sequence is generated by adding the previous two elements. 1, 2, 3, 5, 8, 13,
 *  21, 34, 55, 89, ...
 */

import java.io.*;
import java.util.Scanner;
import java.util.Arrays;

class EvenFibonacciSum {
  public static void evenFibuSum(int n) {
    Scanner s = new Scanner(System.in);
    int[] x = new int[n];
    int i = 0;
    int p = 0;
    int j;
    x[0] = 0;
    x[1] = 1;
    for (i = 2; i < n; i ++) {
      x[i] = x[i-1] + x[i-2];
    }
    System.out.print(Arrays.toString(x));
    System.out.print("\n\t Cutoff: ");
    j = s.nextInt();
    for (i = 0; i < n; i ++) {
      if (x[i] <= j && x[i] % 2 == 0) {
        p = p + x[i];
      };
    }
    System.out.print("\t Sum of even numbers <= Cutoff: "+p);
  }
    
  public static void main(String[] args) {
    int m;
    System.out.print("\t Enter length of sequence: ");
    Scanner s = new Scanner(System.in);
    m = s.nextInt();
    evenFibuSum(m);
  }
}
